backend:
  name: github
  repo: sehyunchung/sehyunchung.github.io
  branch: dev

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow
site_url: https://sehyunchung.dev
show_preview_links: true

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'blog/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'til'
    label: 'TIL'
    folder: 'content/til'
    create: true
    slug: '{{year}}-{{month}}-{{day}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

